language: node_js
sudo: false
node_js:
- 10
install:
- npm i
script: true
deploy:
  provider: npm
  email: gautaz@users.noreply.github.com
  api_key:
    secure: RzbIe9wwfBnRoUQ3TvUuaqfFE46+0R/NF6LEcGCFEeZxt7YQ7EZCe/VHt8tnsGVERxQLaXZP5fONIp0gJNBE05hZTwieRp8xCsEGg0yr05Am1X17M45AYpEVu7x6Jc81/0uIhA44BZI7BosfBwuMEtPogWq1dfeJeyRuJ1iauZYFhn0IICqtlOWcgUPOiNAQB2KCWnKqOM18QPul7VkfOtowrO4L9jlVN5/JaAjbZQP3bPCkuIyX+lkg1OCWnucrc7qVLunOVBiM1ZounB7ZT/SfveQSv9S8JpqoY6XwU5W1GcU/Na48eluBG/2iy4PfxSTEi0fzFPIeOD+5Gowfk/Jd/quA1S2qgul7O8mztvckiP6YTMgw6+wTmW1G2CUdlAom999P2/04jtqleaDdPg1bS9uIYzesvzJ3t/IMvjeDZv3wAHOY4ulBZh5W0pwnlljH31O0tjZeu/W6L6nNkUxN64oPEoFALcrMuB0hG3aU5tEbJJHxd6inGdY8kGFFPSmK8jsUTCSuJDD2esQrM64UxUhgQeriaUTteD9PBUIH4ZagJkiZZOY1o8a3s2bBtayXCBMgJN/LjkoeeyGap6osQiTrve2cILzOGPu9Zcs9BOVVsi+JD73Wh6kdQSA2Zf2Pt+vjhYQqICwKWoV+An4tdNOAPBOnTfaKoVGMe6c=
  on:
    tags: true
    repo: r2d2bzh/js-rules
  skip_cleanup: 'true'
